FROM php:8.2-fpm
WORKDIR /app/backend

# 複製專案檔案到容器中
COPY . .

# 安裝必要的系統套件
RUN apt-get update && apt-get install -y \
  libpng-dev \
  libjpeg-dev \
  libzip-dev \
  zip \
  unzip \
  git \
  default-mysql-client && docker-php-ext-install pdo_mysql gd

# 安裝 Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# 執行 Composer 安裝
RUN composer install --no-scripts

# 生成應用程式金鑰
RUN php artisan key:generate

# 生成自動載入檔案
RUN composer dump-autoload

# 暴露 PHP-FPM 的端口
EXPOSE 9000

# 啟動 PHP-FPM 服務
CMD ["php-fpm"]
