FROM php:8.2-fpm
WORKDIR /app/backend

# 複製專案檔案到容器中
COPY . .

# 安裝必要的系統套件
RUN apt-get update && apt-get install -y \
  libpng-dev \
  libjpeg-dev \
  libzip-dev \
  zip \
  unzip \
  git \
  default-mysql-client && docker-php-ext-install pdo_mysql gd && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && composer install --no-scripts --no-autoloader && comoser update && php artisan key:generate

# 暴露 PHP-FPM 的端口
EXPOSE 9000

# 啟動 PHP-FPM 服務
CMD ["php-fpm"]
